title: Kamil Kot
email: contact@kamilkot.me
description: ""
baseurl: "/"
url: "kamilkot.me"

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

header_pages:
  - about.markdown